# Generated by Django 4.1.1 on 2022-10-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_categoris_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoris',
            new_name='categories',
        ),
    ]
